# Generated by Django 3.2.6 on 2021-08-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgText', models.TextField()),
                ('msgTime', models.DateTimeField()),
            ],
        ),
    ]
