# Generated by Django 3.2.6 on 2021-08-18 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msgText',
            new_name='msgContent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msgTime',
        ),
        migrations.AddField(
            model_name='message',
            name='msgTimestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
