# Generated by Django 3.2.6 on 2021-08-19 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='userCount',
            field=models.ManyToManyField(blank=True, help_text='Currently connected users', to=settings.AUTH_USER_MODEL),
        ),
    ]
