# Generated by Django 3.2.6 on 2021-08-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chatRoom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
